/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScProduct {
        "imagealt"?: string;
        "imagesrc"?: string;
        "productname"?: string;
    }
}
declare global {
    interface HTMLScProductElement extends Components.ScProduct, HTMLStencilElement {
    }
    var HTMLScProductElement: {
        prototype: HTMLScProductElement;
        new (): HTMLScProductElement;
    };
    interface HTMLElementTagNameMap {
        "sc-product": HTMLScProductElement;
    }
}
declare namespace LocalJSX {
    interface ScProduct {
        "imagealt"?: string;
        "imagesrc"?: string;
        "productname"?: string;
    }
    interface IntrinsicElements {
        "sc-product": ScProduct;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sc-product": LocalJSX.ScProduct & JSXBase.HTMLAttributes<HTMLScProductElement>;
        }
    }
}
